---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo
  labels:
    app: react-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-todo
  template:
    metadata:
      labels:
        app: react-todo
    spec:
      containers:
        - name: react-todo
          image: fernandorubens/react-todo
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: react-todo-service
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: react-todo
  type: LoadBalancer
